ROOT_CA_KEY='rca'
INTERMEDIATE_CA_KEY='ica'
CERT_KEY='cert'
PRIV_KEY='sk'

MESSAGE_STORES_KEY = 'MESSAGE_STORES'

PROTOCOL_SUITE_ATIS = 'atis'
PROTOCOL_SUITE_CPEX = 'cpex'

STATUS_PENDING = 'pending'
STATUS_DONE = 'done'