ROOT_CA_KEY='rca'
INTERMEDIATE_CA_KEY='ica'
CERT_KEY='cert'
PRIV_KEY='sk'

MESSAGE_STORES_KEY = 'MESSAGE_STORES'

MODE_ATIS = 'atis'
MODE_CPEX = 'cpex'
MODES = [MODE_ATIS, MODE_CPEX]

STATUS_PENDING = 'pending'
STATUS_DONE = 'done'
