ROOT_CA_KEY='rca'
INTERMEDIATE_CA_KEY='ica'
OTHER_CREDS_KEY='ocrt'
CERT_KEY='cert'
PRIV_KEY='sk'

MESSAGE_STORES_KEY = 'MESSAGE_STORES'

MODE_OOBSS = 'oobss'
MODE_JODI = 'jodi'
MODES = [MODE_OOBSS, MODE_JODI]

STATUS_PENDING = 'pending'
STATUS_DONE = 'done'
