---
- name: Setup and deploy prototype
  hosts: all
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Stop Services
      tags:
        - stop_services
      command: "./scripts/apps.sh down"
      args:
        chdir: "{{ repo_dest }}"

    - name: Clear logs
      tags:
        - clear_logs
      shell: "rm -rf ./logs/*.log ./docker/data/mongo"
      args:
        chdir: "{{ repo_dest }}"

    - name: Start Jodi CPSs
      tags:
        - start_jodi
      command: "./scripts/apps.sh jodi_cps"
      args:
        chdir: "{{ repo_dest }}"
      when: hostvars[inventory_hostname].type == "cps"

    - name: Start Jodi ALS
      tags:
        - start_jodi
      command: "./scripts/apps.sh jodi_als"
      args:
        chdir: "{{ repo_dest }}"
      when: hostvars[inventory_hostname].type == "als"

    - name: Start OOB-S/S Services
      tags:
        - start_oobss
      command: "./scripts/apps.sh oobss"
      args:
        chdir: "{{ repo_dest }}"
      when: hostvars[inventory_hostname].type == "cps"
